(()=>{

const items=[{icon:'▰',name:'5 TB de armazenamento',tag:'Google One',title:'Mais espaço para tudo o que importa',description:'Guarde arquivos, fotos e documentos com 5 TB (5.000 GB) de armazenamento compartilhado entre Gmail, Drive e Google Fotos.',chips:['Drive, Gmail e Fotos','Na sua conta Google','Acesso em seus dispositivos']},{icon:'✉',name:'Assistente de IA no Gmail',tag:'Produtividade',title:'Escreva e organize seus e-mails com IA',description:'Use o Gemini para resumir mensagens, elaborar respostas e revisar textos diretamente no Gmail.',chips:['Resumos','Rascunhos','Revisão de mensagens']},{icon:'✦',name:'Gemini Pro',tag:'Inteligência artificial',title:'Um assistente para sua rotina',description:'Pesquise, desenvolva ideias, analise informações, programe e crie conteúdos com limites ampliados conforme o plano.',chips:['Estudo e pesquisa','Planejamento','Criação']},{icon:'▤',name:'IA no Docs e Planilhas',tag:'Ferramentas de trabalho',title:'IA nas ferramentas que você já usa',description:'Crie documentos, resuma conteúdos e ajude a organizar informações e fórmulas no Docs e no Planilhas.',chips:['Documentos','Resumos','Planilhas']},{icon:'◉',name:'Vídeos com Veo',tag:'Vídeo com IA',title:'Transforme ideias em vídeos',description:'Crie conteúdos visuais a partir de comandos de texto nos recursos compatíveis. O acesso e os limites variam conforme as condições do plano.',chips:['Criação por texto','Recursos compatíveis']},{icon:'∞',name:'Créditos mensais de IA',tag:'Criação',title:'Créditos para explorar ferramentas de IA',description:'A oferta apresenta 1.000 créditos mensais para recursos compatíveis de criação. Consulte a disponibilidade e os limites na ativação.',chips:['1.000 créditos mensais','Recursos compatíveis']},{icon:'▣',name:'NotebookLM',tag:'Estudo e pesquisa',title:'Encontre respostas no seu material',description:'Envie PDFs, livros e documentos para resumir conteúdos e pesquisar informações com base nas fontes que você adicionou.',chips:['Resumos','Documentos','Pesquisa']},{icon:'◌',name:'Antigravity',tag:'Desenvolvimento',title:'Apoio de IA para desenvolver',description:'Planeje, desenvolva e automatize tarefas de programação com agentes de IA, sujeito à disponibilidade e aos limites do plano.',chips:['Código','Agentes de IA','Automação']}];let selected=0;const tabs=document.querySelector('.tabs'),panel=document.querySelector('.detail');const productIcons=[
'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path fill="#00875a" d="M8.2 2h5l8.5 14.7-2.5 4.3-8.5-14.7z"/><path fill="#ffba00" d="M8.2 2h5L4.7 16.7H0z"/><path fill="#4285f4" d="M4.7 16.7h17L19.2 21h-17z"/></svg>',
'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285f4" d="M1 6.5v13h4V9.6z"/><path fill="#34a853" d="M19 9.6v9.9h4v-13z"/><path fill="#ea4335" d="M1 6.5 3.3 4 12 10.8l8.7-6.8L23 6.5l-11 8.4z"/><path fill="#c5221f" d="M1 6.5 3.3 4 5 5.4v4.2z"/><path fill="#fbbc04" d="M19 5.4 20.7 4 23 6.5l-4 3.1z"/></svg>',
'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><defs><linearGradient id="gemini-tab" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#4285f4"/><stop offset=".5" stop-color="#8956c6"/><stop offset="1" stop-color="#ea4335"/></linearGradient></defs><path fill="url(#gemini-tab)" d="M12 1.5c1 6.4 4.1 9.5 10.5 10.5-6.4 1-9.5 4.1-10.5 10.5C11 16.1 7.9 13 1.5 12 7.9 11 11 7.9 12 1.5z"/></svg>',
'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285f4" d="M5 1h10l5 5v17H5a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2z"/><path fill="#a1c2fa" d="M15 1v5h5z"/><path stroke="white" stroke-width="1.5" d="M7 12h10M7 15h10M7 18h7"/></svg>',
'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="10" fill="#9b5cf6"/><path fill="white" d="m10 7 7 5-7 5z"/></svg>',
'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path fill="#6659e9" d="M4 8c2-2 4-2 6 0l2 2 2-2c2-2 4-2 6 0l2 2-2 2c-2 2-4 2-6 0l-2-2-2 2c-2 2-4 2-6 0l-2-2z"/></svg>',
'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="2" width="18" height="20" rx="3" fill="#1a73e8"/><rect x="7" y="5" width="10" height="14" rx="1" fill="white"/><path fill="#1a73e8" d="M9 8h6v2H9zm0 4h6v2H9z"/></svg>',
'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3" fill="#6657ed"/><path d="M4 11a8 8 0 0 1 12-6M20 13a8 8 0 0 1-12 6M2 17c4 3 12-1 16-5s5-8 4-9" fill="none" stroke="#6657ed" stroke-width="1.8" stroke-linecap="round"/></svg>'
];function demo(i){if(i===0)return '<div class="resource-demo"><h4>▰ Google Drive · Gmail · Google Fotos</h4><div class="demo-big">5 TB</div><span class="demo-sub">Equivalente a 5.000 GB de armazenamento</span><div class="bar"></div></div>';if(i===1)return '<div class="resource-demo"><h4>✉ Assistente de IA no Gmail</h4><p><b>Resumo da mensagem</b><br>Entenda os pontos principais de um e-mail longo e prepare uma resposta com ajuda do Gemini.</p></div>';if(i===2)return '<div class="resource-demo dark-demo"><h4>✦ Gemini Pro</h4><div class="code">&gt; Como posso organizar este projeto?<br><br>Estruture objetivos, etapas, prazos e próximos passos com ajuda da IA.</div></div>';if(i===3)return '<div class="resource-demo"><h4>▤ Docs e Planilhas</h4><p><b>Documento:</b> crie um resumo claro do material.<br><br><b>Planilha:</b> organize dados e formule análises.</p></div>';if(i===4)return '<div class="resource-demo"><h4>▶ Criação de vídeo com IA</h4><p>Descreva uma cena em texto e explore os recursos compatíveis de geração de vídeo.</p></div>';if(i===5)return '<div class="resource-demo"><h4>Créditos mensais</h4><div class="demo-big">1.000</div><span class="demo-sub">Para recursos de IA compatíveis, conforme as condições do plano.</span></div>';if(i===6)return '<div class="resource-demo"><h4>▣ NotebookLM</h4><p>Adicione documentos e encontre respostas fundamentadas nos seus próprios materiais.</p></div>';return '<div class="resource-demo"><h4>◌ Agentes de IA</h4><p>Planeje, programe e automatize tarefas em um ambiente de desenvolvimento assistido.</p></div>'}function render(){tabs.innerHTML=items.map((x,i)=>`<button type="button" role="tab" id="tab-${i}" aria-controls="resource-panel" aria-selected="${i===selected}" tabindex="${i===selected?0:-1}" data-index="${i}"><span>${productIcons[i]}${x.name}</span><span aria-hidden="true">›</span></button>`).join('');let x=items[selected];panel.id='resource-panel';panel.setAttribute('aria-labelledby',`tab-${selected}`);panel.innerHTML=`<span class="eyebrow">${x.tag}</span><h3>${x.title}</h3><p>${x.description}</p>${demo(selected)}`}tabs.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;selected=Number(b.dataset.index);render()});tabs.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;e.preventDefault();selected=e.key==='Home'?0:e.key==='End'?items.length-1:(selected+(e.key==='ArrowLeft'||e.key==='ArrowUp'?-1:1)+items.length)%items.length;render();tabs.querySelector('[aria-selected=true]').focus()});render();

})();
